-- This is the schemas for Supabase database

create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  message_id text unique nulls not distinct,  -- so NULLs from manual entries can repeat
  category_id bigint references public.categories(id) on delete set null,
  transacted_at timestamptz not null,
  direction text check (direction in ('incoming','outgoing')) not null,
  amount numeric(12,2) not null,
  currency text,
  description text,
  from_account text,
  to_account text,
  mode_of_payment text,
  provider text,
  bank text,
  source text default 'gmail',
  gmail_from text,
  gmail_to text,
  created_at timestamptz not null default now()
);
create unique index transactions_message_id_idx
  on public.transactions (message_id) where message_id is not null;

create table public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  monthly_budget numeric(12,2) not null default 0,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table public.user_settings (
    user_id uuid primary key references auth.users (id) on delete cascade,
    transaction_email text not null,
    use_default_supabase boolean not null default true,
    custom_supabase_url text,
    custom_supabase_anon_key text,
    notifications_enabled boolean not null default true,
    updated_at timestamptz not null default timezone('utc', now())
);

alter table public.user_settings enable row level security;

create policy "Users read their settings"
  on public.user_settings
  for select
  using (auth.uid() = user_id);

create policy "Users insert their settings"
  on public.user_settings
  for insert
  with check (auth.uid() = user_id);

create policy "Users update their settings"
  on public.user_settings
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users delete their settings"
  on public.user_settings
  for delete
  using (auth.uid() = user_id);
